In [147]:
# Import librarys
import pandas as pd
import numpy as np

In [148]:
# Read in csv
df = pd.read_csv('./data/test.csv')

df.head()

,Year,Section,Question,Letter,Part,Marks,Page,Subject,Marking Instruction Page,Marking Instruction Pages,Notes
0,2014,a,1.0,NaN,NaN,1.0,3.0,Electricity 1. Electrical charge carriers and ...,NaN,NaN,NaN
1,2014,a,2.0,NaN,NaN,1.0,3.0,Electricity 3. Practical electrical and electr...,NaN,NaN,NaN
2,2014,a,3.0,NaN,NaN,1.0,4.0,Electricity 3. Practical electrical and electr...,NaN,NaN,NaN
3,2014,a,4.0,NaN,NaN,1.0,5.0,Dynamics 5. Conservation of energy,NaN,NaN,NaN
4,2014,a,5.0,NaN,NaN,1.0,5.0,Properties of Matter 3. Gas laws and the kinet...,NaN,NaN,NaN

In [149]:
# Create new df with only Section B questions
dfb = df[df['Section'] == 'b'].copy()

# Fill NaN values with empty string
dfb = dfb.fillna('')

# Convert numbers into integers
dfb = dfb.astype({'Question': int, 'Marks': int, 'Page': int})

# Join 3 questions columns together into 1 new column
dfb["FullQuestion"] = dfb[['Question', 'Letter', 'Part']].agg(lambda x: ''.join(str(v) for v in x), axis=1)

In [150]:
# Group questions together by topic
gp = dfb.groupby(['Subject', 'Year']).aggregate({'FullQuestion':lambda x: ', '.join(str(v) for v in x)})
gp.head()

                                                                            FullQuestion
Subject                                            Year
Dynamics 1. Vectors and scalars                    2014                       10bii, 11c
Dynamics 2. Velocity-time graphs                   2014                10ai, 10aii, 10bi
Dynamics 4. Newton's laws                          2014  10aiii, 11a, 11b, 12a, 12c, 12d
Dynamics 5. Conservation of energy                 2014                          3a, 12e
Electricity 3. Practical electrical and electro... 2014   1a, 1bii, 1bii, 2ai, 2bi, 2bii

In [151]:
gp.to_csv('./csvs/output.csv')