In [48]:
# Import librarys
import pandas as pd
import numpy as np

In [49]:
# Read in csv
df = pd.read_csv('./data/test.csv')

df.head()

,Year,Section,Question,Letter,Part,Marks,Page,Subject,Marking Instruction Page,Marking Instruction Pages,Notes
0,2014,a,1.0,NaN,NaN,1.0,3.0,Electricity 1. Electrical charge carriers and ...,7.0,1.0,NaN
1,2014,a,2.0,NaN,NaN,1.0,3.0,Electricity 3. Practical electrical and electr...,7.0,1.0,NaN
2,2014,a,3.0,NaN,NaN,1.0,4.0,Electricity 3. Practical electrical and electr...,7.0,1.0,NaN
3,2014,a,4.0,NaN,NaN,1.0,5.0,Dynamics 5. Conservation of energy,7.0,1.0,NaN
4,2014,a,5.0,NaN,NaN,1.0,5.0,Properties of Matter 3. Gas laws and the kinet...,7.0,1.0,NaN

In [50]:
# Create new df with only Section B questions
dfab = df[(df['Section'] == 'b') | (df['Section'] == 'a')].copy()

# Fill NaN values with empty strings
dfab = dfab.fillna('')

# Convert numbers into integers
dfab = dfab.astype({'Question': int, 'Marks': int, 'Page': int})

# Join 3 questions columns together into 1 new column
dfab["FullQuestion"] = dfab[['Question', 'Letter', 'Part']].agg(lambda x: ''.join(str(v) for v in x), axis=1)

dfab.head()

,Year,Section,Question,Letter,Part,Marks,Page,Subject,Marking Instruction Page,Marking Instruction Pages,Notes,FullQuestion
0,2014,a,1,,,1,3,Electricity 1. Electrical charge carriers and ...,7.0,1.0,,1
1,2014,a,2,,,1,3,Electricity 3. Practical electrical and electr...,7.0,1.0,,2
2,2014,a,3,,,1,4,Electricity 3. Practical electrical and electr...,7.0,1.0,,3
3,2014,a,4,,,1,5,Dynamics 5. Conservation of energy,7.0,1.0,,4
4,2014,a,5,,,1,5,Properties of Matter 3. Gas laws and the kinet...,7.0,1.0,,5

In [53]:
# Group questions together by topic
gp = dfab.groupby(['Subject', 'Year', 'Section']).aggregate({'FullQuestion':lambda x: ', '.join(str(v) for v in x)})

# Unstack headings
gp = gp.unstack()

# Fill NaN values with empty strings
gp = gp.fillna('')

gp.head()

                                        FullQuestion  \
Section                                            a
Subject                            Year
Dynamics 1. Vectors and scalars    2014       14, 15
Dynamics 2. Velocity-time graphs   2014
Dynamics 3. Acceleration           2014
Dynamics 4. Newton's laws          2014           17
Dynamics 5. Conservation of energy 2014        4, 16


Section                                                                b
Subject                            Year
Dynamics 1. Vectors and scalars    2014                       10bii, 11c
Dynamics 2. Velocity-time graphs   2014                      10aii, 10bi
Dynamics 3. Acceleration           2014                             10ai
Dynamics 4. Newton's laws          2014  10aiii, 11a, 11b, 12a, 12c, 12d
Dynamics 5. Conservation of energy 2014                          3a, 12e

In [54]:
gp.to_csv('./csvs/output.csv')